server:
  port: 56010
spring:
  application:
    name: quickstart-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
logging:
  level:
    root: info
    org.springframework: info