server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: mysql://localhost:3306/github?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver